language: python
python:
  - "3.6"
install:
  - pip install cython
  - pip install scipy	
  - pip install scikit-learn	
  - pip install matplotlib	
  - pip install pyyaml
script:
  - python setup.py build_ext --inplace
  - pytest
