[build-system]
requires = ["setuptools", "setuptools_scm", "wheel", "numpy", "Cython"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
#local_scheme = "no-local-version"
#write_to = "harmonic/_version.py"